# This file contains all the animations that the game uses
# The animations were all done by us
# However, the final ASCII Art, i.e. the art which is shown
# is generated by different websites
# Websites used to generate the art  have been credited in
# the relevant lines when used
# We have also used the aid of one of the answers in 
# StackOverflow, (precisely, https://stackoverflow.com/questions/2084508/clear-terminal-in-python)
# to aid us in learning how to clear the terminal
 

# os is used for clearing terminal
# time is used for the timings and animation effect


import os
import time


def printOpeningScreen():
    # Prints the opening screen animation

    os.system('cls' if os.name == 'nt' else 'clear') # Clears Terminal
    print('''
                                            _                                                 _  
                                           | |                                               | | 
                                           | |                                               | | 
                                           | |                                               | | 
                                           | |____                                           |_| 
                                           |______|                                          (_) 
                                                                                  
                                                                             
    ''') # Will print step by step
    time.sleep(0.75) # This will prevent the instantaneous change of output

    os.system('cls' if os.name == 'nt' else 'clear')
    print('''
                                            _      _                                      _   _  
                                           | |    (_)                                    | | | | 
                                           | |     _  __ _                          _   _| |_| | 
                                           | |    | |/ _` |                        | | | | __| | 
                                           | |____| | (_| |                        | |_| | |_|_| 
                                           |______|_|\__, |                         \__,_|\__(_) 
                                                      __/ |                                      
                                                     |___/    
    ''')
    time.sleep(0.75)

    os.system('cls' if os.name == 'nt' else 'clear')
    # The following ASCII art was generated from
    # https://patorjk.com/software/taag
    print('''
                                            _      _       _     _   _        ____        _   _  
                                           | |    (_)     | |   | | ( )      / __ \      | | | | 
                                           | |     _  __ _| |__ | |_|/ ___  | |  | |_   _| |_| | 
                                           | |    | |/ _` | '_ \| __| / __| | |  | | | | | __| | 
                                           | |____| | (_| | | | | |_  \__ \ | |__| | |_| | |_|_| 
                                           |______|_|\__, |_| |_|\__| |___/  \____/ \__,_|\__(_) 
                                                      __/ |                                      
                                                     |___/                                       
    ''')
    time.sleep(1)

    os.system('cls' if os.name == 'nt' else 'clear')
    print('''
   
        
                                           | |     _  __ _| |__ | |_|/ ___  | |  | |_   _| |_| | 
                                           | |    | |/ _` | '_ \| __| / __| | |  | | | | | __| | 
                                           | |____| | (_| | | | | |_  \__ \ | |__| | |_| | |_|_| 
                                           |______|_|\__, |_| |_|\__| |___/  \____/ \__,_|\__(_) 
    
    
    ''')
    time.sleep(0.75)

    os.system('cls' if os.name == 'nt' else 'clear')
    print('''



                                           | |    | |/ _` | '_ \| __| / __| | |  | | | | | __| | 
                                           | |____| | (_| | | | | |_  \__ \ | |__| | |_| | |_|_| 



    ''')
    time.sleep(0.75)

    os.system('cls' if os.name == 'nt' else 'clear')
    time.sleep(0.5)


def printBulbForwardLoad():
    # Prints the bulb animation used multiple times

    os.system('cls' if os.name == 'nt' else 'clear')
    # This ASCII art was partially made through
    # https://www.asciiart.eu/image-to-ascii
    # However, it was slightly amended to fit the screen size
    print("""                              
                                                            @                                             
                                               @@           @         @@                   
                                                 @    @@@@@@@@@@@@@   @                     
                                                    @@@           @@@                        
                                                  @@                 @@                                 
                                                 @@                   @@           
                                       @@@@@@@   @@                   @@   @@@@@@                
                                                 @@                   @@                                  
                                                   @@               @@                                
                                                 @   @             @   @                   
                                               @@    @@           @@    @@                 
                                              @@     @@           @@      @@               
                                                      @@@@@@@@@@@@@                                               
                                                       @@@@@@@@@@@                         
                                                       @@@@@@@@@@@                                                
    """)
    time.sleep(0.9)

    os.system('cls' if os.name == 'nt' else 'clear')
    print("""                              
                                                            @                                             
                                               @@           @         @@                   
                                                 @    @@@@@@@@@@@@@   @                     
                                                    @@@           @@@                        
                                                  @@                 @@                                 
                                                 @@                   @@           
                                       @@@@@@@   @@                   @@   @@@@@@                
                                                 @@                   @@                                  
                                                   @@               @@                                
                                                     @             @                     
                                                     @@           @@                     
                                                     @@           @@                   
                                                      @@@@@@@@@@@@@                                               
                                                       @@@@@@@@@@@                         
                                                       @@@@@@@@@@@                                                  
    """)
    time.sleep(0.9)

    os.system('cls' if os.name == 'nt' else 'clear')
    print("""                                             
                                                            @                                             
                                                            @                           
                                                      @@@@@@@@@@@@@                        
                                                    @@@           @@@                        
                                                  @@                 @@                                 
                                                 @@                   @@           
                                       @@@@@@@   @@                   @@   @@@@@@                
                                                 @@                   @@                                  
                                                   @@               @@                                
                                                     @             @                     
                                                     @@           @@                     
                                                     @@           @@                   
                                                      @@@@@@@@@@@@@                                               
                                                       @@@@@@@@@@@                         
                                                       @@@@@@@@@@@                                        
    """)
    time.sleep(0.9)

    os.system('cls' if os.name == 'nt' else 'clear')
    print("""                              
                                                                           
                                                          
                                                      @@@@@@@@@@@@@                        
                                                    @@@           @@@                        
                                                  @@                 @@                                 
                                                 @@                   @@           
                                                 @@                   @@                  
                                                 @@                   @@                                  
                                                   @@               @@                                
                                                     @             @                     
                                                     @@           @@                     
                                                     @@           @@                   
                                                      @@@@@@@@@@@@@                                               
                                                       @@@@@@@@@@@                         
                                                       @@@@@@@@@@@                        
                                 
    """)
    time.sleep(0.5)

    os.system('cls' if os.name == 'nt' else 'clear')
    time.sleep(0.5)


def returningToLobby():
  # When the user returns to Lobby
  # This animation will serve as a standard
  # and will provide a more game-like effect

  for i in range(3, 0, -1):
    os.system('cls' if os.name == 'nt' else 'clear')
    print("                                                                              ")
    print("                                                                              ")
    print("                              ---------------------------------------------------------------")
    print("                                                                              ")
    print("                                                                              ")
    print(f"                                              Returning to lobby in.........{i}              ")
    print("                                                                              ")
    print("                                                                              ")
    print("                              ---------------------------------------------------------------")
    time.sleep(1)


def endAnimation():
  # This is similar to printOpeningScreen but is basically reversed

  os.system('cls' if os.name == 'nt' else 'clear')
  print('''



                                         | |    | |/ _` | '_ \| __| / __| | |  | | | | | __| | 
                                         | |____| | (_| | | | | |_  \__ \ | |__| | |_| | |_|_| 



  ''')
  time.sleep(0.75)

  os.system('cls' if os.name == 'nt' else 'clear')
  print('''
  
      
                                         | |     _  __ _| |__ | |_|/ ___  | |  | |_   _| |_| | 
                                         | |    | |/ _` | '_ \| __| / __| | |  | | | | | __| | 
                                         | |____| | (_| | | | | |_  \__ \ | |__| | |_| | |_|_| 
                                         |______|_|\__, |_| |_|\__| |___/  \____/ \__,_|\__(_) 
  
  
  ''')
  time.sleep(0.75)

  os.system('cls' if os.name == 'nt' else 'clear')
  # The following ASCII art was generated from
  # https://patorjk.com/software/taag
  print('''
                                          _      _       _     _   _        ____        _   _  
                                         | |    (_)     | |   | | ( )      / __ \      | | | | 
                                         | |     _  __ _| |__ | |_|/ ___  | |  | |_   _| |_| | 
                                         | |    | |/ _` | '_ \| __| / __| | |  | | | | | __| | 
                                         | |____| | (_| | | | | |_  \__ \ | |__| | |_| | |_|_| 
                                         |______|_|\__, |_| |_|\__| |___/  \____/ \__,_|\__(_) 
                                                    __/ |                                      
                                                   |___/                                       
  ''')
  time.sleep(1)

  os.system('cls' if os.name == 'nt' else 'clear')
  print('''
                                          _      _                                      _   _  
                                         | |    (_)                                    | | | | 
                                         | |     _  __ _                          _   _| |_| | 
                                         | |    | |/ _` |                        | | | | __| | 
                                         | |____| | (_| |                        | |_| | |_|_| 
                                         |______|_|\__, |                         \__,_|\__(_) 
                                                    __/ |                                      
                                                   |___/    
  ''')
  time.sleep(0.75)

  os.system('cls' if os.name == 'nt' else 'clear')
  print('''
                                          _                                                 _  
                                         | |                                               | | 
                                         | |                                               | | 
                                         | |                                               | | 
                                         | |____                                           |_| 
                                         |______|                                          (_) 
                                                                                
                                                                            
  ''')
  time.sleep(0.75)

  os.system('cls' if os.name == 'nt' else 'clear')
  time.sleep(0.5)
